/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CareRecipientsFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MedicationApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MedicationManagerUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "MedicationManagerWebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "MedicationsFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MySql": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Mysql"
      "username": string
    }
    "UserFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "WebApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}